alphagov/passport-verify-stub-relying-party

acceptance-tests/acceptance-tests.ts, package.json, src/app.ts, src/index.ts, test/authenticate-test.ts, yarn.lock
This means no longer passing a logger to the library, which now uses the 'debug' package.
Authors: @rachaelbooth
=> TT-999 Updated to use version 0.8.0 of passport-verify

README.md, acceptance-tests/acceptance-tests.ts, package.json, pre-commit.sh, startup.sh
Shell scripts now run a single npm script.
Replaced *-paas scripts with a --paas flag.
Removed some duplication within scripts.
Authors: @rachaelbooth
=> TT-1140 - Improve scripts

acceptance-tests/acceptance-tests.ts, package.json, src/views/view-attributes.njk, yarn.lock
This adds address history display. 
It does work with the current version of passport-verify (because javascript), but should version bump once the interface updates there are merged/deployed.
=> TT-1215 Displays address history attribute in view-attributes if present

.travis.yml, docker-build.sh, pre-commit.sh, vsp.Dockerfile
- fix inability to start vsp in travis by removing wildcard in `cd`
command
- using docker volumes in Jenkins job was introducing root ownership of
build directory in Jenkins Workspace.
authors: @sgreensmith @SKeerthana
=> TT-1837 bug fixes in build and deployment pipeline

.travis.yml, src/app.ts
In the latest version of the nodejs buildpack on PaaS the location of
the node_modules directory has changed. Previously the code assumed it
would be in `./node_modules` relative to the current working directory.
It's now in `/deps/0/node_modules` on PaaS.
This causes an issue where the views can't find the govuk_template
template.
Instead of relying on the node script being run from a certain directory
we can use [require.resolve](https://nodejs.org/api/modules.html#modules_require_resolve_request_options)
to look up the path to the module using node's resolution algorithm. We
then have to be a bit hacky and go up a couple of directories to get the
`views` dir that we were configuring nunjucks to use before.
Hopefully this should fix the PaaS apps.
=> bau: Fix template lookup on PaaS

src/app.ts
As described in 8612941 the location of node_modules is different in the
latest nodejs buildpack used by PaaS. We'd fixed one of these issues
using require.resolve, but we'd missed the same issue 5 lines further
down.
I've done a `git grep` for `node_modules` and I'm pretty sure this is
the last one.
=> bau: Fix asset loading on PaaS

package.json
Specifying 6.14.1 exactly prevents this from running on the PaaS as
support for 6.14.1 has been removed in a recent buildpack upgrade.
By specifying 6.x instead we'll be able to deploy until the entire node
6 version line drops out of support, at which point we should really
upgrade.
=> Relax package.json "engines" constraint

dev-manifest-multi-one.yml, dev-manifest-multi-two.yml, dev-manifest.yml
Deplyoments have been failing for a while using these manifests. I think
this might be due to changes in nodejs buildpack that we haven't
accounted for.
=> YmnUf9Ma: fix deployment to cloud foundry

src/index.ts
The `matching` environment flag returns as a string, not boolean
so the current if statement was evaluating to true whenever it was set and starting the app in a matching mode.
This should fix it.
=> BAU: Fix the initialization condition

src/app.ts
I enabled the eIDAS in hub, but forgot we're using LOA1 :doh: ...
This changes it to LOA2 so eIDAS should work
=> fSYu2psF: Add eidas E2E tests

e2e-tests/e2e-tests.ts
Sometimes the matching process and the meta-refresh on `/response-processing` takes longer than the current delay so the matching tests can be flaky
=> edKsCW79: add a delay to accommodate slow matching

src/views/view-identity-attributes.njk
For non-matching attributes we're now returning most of them as lists with historic values.
=> TyGN7itP: Update view to reflect the updated attributes

package.json
After the recent changes we published a new release candidate version of passport-verify.
=> BAU: Bump passport-verify dependency

package.json, yarn.lock
We've used the RC version of passport-verify for testing. Given we have now released
it properly, we should be using that version.
=> BAU: Use the released version of passport-verify

acceptance-tests/verify-service-provider-with-matching.yml, vsp.Dockerfile
The acceptance tests are written againts the compliance tool. The tests use the
latest released version of VSP which now by default uses non-matching.
However, compliance tool does not support non-matching. This is to add
matching config for VSP when running the acceptance test. In future we should revisit
to see whether we want to still use the compliance tool for this scenario.
This should make the build green.
=> BAU: Fix the acceptance tests

package.json, yarn.lock
Update outdated dependencies along with fixing some vulnerabilities:
`WS-2019-0032` - Versions js-yaml prior to 3.13.0 are vulnerable to Denial of Service.
`WS-2019-0063` - Js-yaml prior to 3.13.1 are vulnerable to Code Injection
`CVE-2017-16042` - Growl before 1.10.0 does not properly sanitize input before passing it to exec, allowing for arbitrary command execution.
=> BAU: Update dependencies

ci/puppeteer.Dockerfile
A new Chromium version (used to run e2e tests) has now more dependencies, so
adding them to the container for the puppeteer tests to go green.
As per:
(https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine)
=> BAU: Update puppeteer Docker image

package.json
The tests are now passing but the latest Mocha version introduced a breaking change
when it doesn't exit even if the test passes.
So the tests are passing but not exiting :face_with_rolling_eyes:
This adds the `--exit` flag to tell Mocha to exit when finished testing.
https://github.com/mochajs/mocha/issues/3044
=> BAU: Fix E2E tests

README.md, vsp.Dockerfile
- Use the standard openjdk root docker image so it can run on jdk11
- Update README 
- This will allow us to stop using the custom Verify docker images
=> BAU - Use stanard openjdk 11 docker image

e2e-tests/e2e-tests.ts
You can run these tests locally against integration:
Install yarn if you don't have it with `$ brew install yarn`, then
```
$ yarn install
$ export E2E_TEST_ENVIRONMENT=https://passport-verify-stub-relying-party-integration.cloudapps.digital
$ yarn run e2e-tests:non-matching
```
The VSP has been updated to handle unsigned assertions from eIDAS
countries and we should reflect that in these tests, using new
functionality on stub-country.
=> EID-1731 Extend acceptance tests for unsigned assertions

ci/puppeteer.Dockerfile, package.json, yarn.lock
Currently the `puppeteer-image` task [in the VSP release pipeline is
broken.](https://deployer.tools.signin.service.gov.uk/teams/main/pipelines/verify-service-provider/jobs/puppeteer-image/builds/7)
This is because it tries to build the puppeteer Docker image, which
falls over when trying to install its chromium dependency.
We're currently installing chromium from the edge distribution. The
available versions here change quickly, and [older versions aren't
maintained](https://medium.com/@stschindler/the-problem-with-docker-and-alpines-package-pinning-18346593e891)
which leads to things breaking.
The reason we're installing from edge, is that the version of puppeteer
we're using is [dependant on at least version 73.0.3679.0 of chromium.](https://github.com/GoogleChrome/puppeteer/releases/ta …
=> BAU Downgrade Puppeteer to v1.11.0

docker-compose.yml
This change fixes the following error by adding POSTGRES_HOST_AUTH_METHOD=trust to the docker-compose.yml file.
```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
connections without a password. This is *not* recommended.
See PostgreSQL documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
```
Author: @adityapahuja
=> BAU: Fix PostgreSQL database error

acceptance-tests/acceptance-tests.ts
Compliance tool is using the new URL address ""https://compliance-tool-integration.cloudapps.digital""; and it no longer needs the old URL address "https://compliance-tool-reference.ida.digital.cabinet-office.gov.uk";. New version of Verify Service Provider is using the new URL address.
COMPLIANCE_TOOL_HOST is set to the hardcoded URL address `https://compliance-tool-reference.ida.digital.cabinet-office.gov.uk`. Since Verify Service Provider (VSP) has been changed to use the new compliance tool URL address `https://compliance-tool-integration.cloudapps.digital`, COMPLIANCE_TOOL_HOST needs to be changed. This change adds an environment variable 'COMPLIANCE_TOOL_URL' which will be used to set COMPLIANCE_TOOL_HOST. The default value for COMPLIANCE_TOOL_HOST is still …
=> BAU: Make compliance tool url configurable

e2e-tests/e2e-tests.ts
The [pipeline](https://cd.gds-reliability.engineering/teams/verify/pipelines/verify-service-provider/jobs/test-integration-e2e/builds/10) is currently broken, because it testing for eIDAS journeys which no longer exists
=> BAU: remove eidas tests from e2e-test

acceptance-tests/acceptance-tests.ts, docker-compose.yml
Test was failing because it was defaulting to the old 'https://compliance-tool-reference.ida.digital.cabinet-office.gov.uk/SAML2/SSO' the new one is 'https://compliance-tool-integration.cloudapps.digital/SAML2/SSO' 
Please see: https://github.com/alphagov/passport-verify-stub-relying-party/pull/62
=> BAU: specify compliance url

Dockerfile, ci/puppeteer.Dockerfile, db.Dockerfile, vsp.Dockerfile
We've moved back to using Docker Hub rather than GHCR
Signed-off-by: Chris Mills <7100370+chriscoffee@users.noreply.github.com>
=> [HUB-841] Use Docker Hub rather than GHCR

ci/dev-manifest-multi-one.yml, ci/dev-manifest-multi-two.yml, ci/dev-manifest.yml, ci/integration-manifest.yml, docker-compose.yml
- Use the database Dockerfile to build the test-db service when running passport tests
- Use older version of the nodejs buildpack that still supports node version 10
=> BAU: Fix passport stub deployment
